# Build stage
FROM python:3.10-slim as builder

WORKDIR /app

# Cài đặt các công cụ build
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc sqlite3

# Cài đặt dependencies
COPY requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /app/wheels -r requirements.txt

# Final stage
FROM python:3.10-slim

# Cài đặt sqlite3
RUN apt-get update && apt-get install -y --no-install-recommends sqlite3 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Sao chép wheels từ build stage
COPY --from=builder /app/wheels /wheels
RUN pip install --no-cache /wheels/*

# Thiết lập biến môi trường
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    DEBUG=False

# Sao chép mã nguồn 
COPY . .

# Chạy script tạo từ điển
RUN python -m scripts.create_dictionary

# Tạo người dùng không có quyền root
RUN adduser --disabled-password --gecos '' appuser
USER appuser

# Mở cổng cho FastAPI
EXPOSE 8800

# Tạo thư mục data và đảm bảo quyền ghi
RUN mkdir -p /app/data && chmod 777 /app/data

# Thêm script khởi tạo database
COPY scripts/init_database.sh /app/scripts/
RUN chmod +x /app/scripts/init_database.sh

# Cập nhật CMD nếu cần thiết
CMD ["/bin/bash", "-c", "/app/scripts/init_database.sh && gunicorn main:app --bind 0.0.0.0:8800 --worker-class uvicorn.workers.UvicornWorker --workers 4"]